version: '3'

services:

  reverse:
    image: nginx:1.17.10
    container_name: reverse
    depends_on:
        - fortune-teller
        - lucky-number
    volumes:
      - ./reverse/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  fortune-teller:
    image: grrrrnt/fortune-teller
    container_name: fortune-teller
    build:
      context: ./fortune_teller
    depends_on:
      - lucky-number
    ports:
      - 8080:80
    restart: on-failure

  lucky-number:
    image: grrrrnt/lucky-number
    container_name: lucky-number
    build:
      context: ./lucky_number
    ports:
      - 5001:5001
    restart: on-failure
